{
 "title": "Product243-河边走用户分析",
 "time": { "from": "now/d", "to": "now/d" },
 "panels": [
  {
   "title": "访问总数",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"count\") FROM \"productdetail_metric\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "产品详情-访问趋势",
   "type": "graph",
   "gridPos": { "h": 10, "w": 18, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "访问计数" }
   ],
   "targets": [
    {
     "alias": "产品详情页",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"count\") FROM \"productdetail_metric\" WHERE $timeFilter GROUP BY time(5m) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "独立用户数",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(DISTINCT(userId)) FROM \"productdetail_metric\" WHERE $timeFilter fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "产品详情-用户访问率",
   "type": "table",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "userId" ], "type": "tag" }
     ],
     "measurement": "productdetail_metric",
     "query": "SELECT SUM(\"count\") FROM \"productdetail_metric\" WHERE $timeFilter GROUP BY \"userName\" limit 500",
     "select": [
      [
       { "params": [ "count" ], "type": "field" }
      ]
     ]
    }
   ]
  }
 ]
}