{
 "title": "Product243-UserDetail",
 "time": { "from": "now/w", "to": "now/w" },
 "templating": {
  "list": [
   { "name": "userName", "query": "15010223310" }
  ]
 },
 "panels": [
  {
   "title": "产品详情-用户访问",
   "type": "graph",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "访问数",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"count\") FROM \"productdetail_metric\" WHERE $timeFilter AND userName='$userName' GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "访问产品总数",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 11 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  COUNT(DISTINCT(resourceCode)) FROM \"productdetail_metric\" WHERE $timeFilter AND userName='$userName' fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "用户访问总数",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 5, "y": 11 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT SUM(\"count\") FROM \"productdetail_metric\" WHERE $timeFilter AND userName='$userName' fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "用户访问-产品列表",
   "type": "table",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 11 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT  DISTINCT(resourceCode) FROM \"productdetail_metric\" WHERE $timeFilter   AND userName='$userName'  GROUP BY time(1d) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  }
 ]
}